### ISSUE TITLE
Questions about subroutine Spring_IMK_RC.tcl

### ISSUE THREAD

**Issue by shakeri-aliakbar** [amaelkady/FM-2D#1]
@amaelkady 
Hi,

Two questions:
In subroutine Spring_IMK_RC.tcl:
https://github.com/amaelkady/FM-2D/blob/master/src/Spring_IMK_RC.tcl

1.Ke is not modified by (n+1) !
2.lambda is not multiplied by theta_p !

**Comment by amaelkady** [comment]
@shakeri-aliakbar the Ke values is passed to the subroutine and not modified inside. For lambda, if the computed lambda is the lower-case lamda then it should be multiopled by theta_p. If that is the case, please feel free to modify the subroutine. Please also note that FM-2D RC modeling is in beta testing.
