### ISSUE TITLE
Error creating folders

### ISSUE THREAD

**Issue by liomessi-10** [amaelkady/FM-2D#2]
Greetings Mr. Elkady, I am trying to replicate the example shown in the videos, but I keep getting this error:

Error Identifier:   MATLAB:cd:NonExistentFolder
Error Message:      Cannot CD to C:\Users\Acer Nitro 5\Desktop\MRF_Example\Results\120111 (Name is nonexistent or not a directory).
--------------------------------------------------
Error Location:
----------------
Line    5 in Read_Analysis_Data
Line  119 in Run_OpenSEES
Line   64 in Execution_Commands
Line  306 in FM2D_App.RunModelButtonPushed

Thanks in advance.

**Comment by amaelkady** [comment]
@liomessi-10 This error means that FM-2D did not generate the results which means that OpenSees did not run properly. Please make sure that the Opensees.exe is working in the installation directory. If so, please make sure to run FM-2D as adminstrator using the FM-2D.exe file in the installation directory.

**Comment by liomessi-10** [comment]
Thank you for the answer, OpenSees.exe is working fine, as the manual suggested I did placed the lib folder within the "...\University of Southampton\FM_2D" directory, I am a windows user. I did full installation of FM-2D in two different PCs and got the same error log, so any help would be appreciated.

**Comment by amaelkady** [comment]
@liomessi-10 Did the analysis run prior to the error?

**Comment by liomessi-10** [comment]
Thank you for the answer, no, the analysis did not run. After I complete the imput in the "Model Parameters" and "Building Parameters" tabs, and click "Get period" the program FM-2D display the message "Error has ocurred! Please see Error file!".

**Comment by amaelkady** [comment]
@liomessi-10 what version are you running

**Comment by liomessi-10** [comment]
Thank you for the answer, version are: FM-2D v1.2111, OpenSees  3.2.1 (included in FM-2D).

**Comment by amaelkady** [comment]
@liomessi-10 this is an old release. Please download the latest fm-2d version and re-install.

**Comment by liomessi-10** [comment]
Thank you for the answer, I can confirm the same error using FM-2D v1.2307. Also the FM-2D/OpenSees window displays the same message:
couldn't read file "DisplayModel3D.tcl": no such file or directory 
  while executing 
"source DisplayModel3D.tcl"
(file "TempModel.tcl" line 41)

**Comment by amaelkady** [comment]
@liomessi-10 is the "DisplayModel3D.tcl" file present in the installlation folder?

**Comment by liomessi-10** [comment]
Thank you for the answer, yes, within the "application" folder.

**Comment by amaelkady** [comment]
@liomessi-10 please send your .mat project file

**Comment by liomessi-10** [comment]
[MRF_example.zip](https://github.com/amaelkady/FM-2D/files/12021550/MRF_example.zip)

**Comment by amaelkady** [comment]
@liomessi-10 the model seems to work fine. I'm not sure what is exactly the issue. One thing I noticed, you have incorrectly defined the loads using ksi units. The loads must be defined in psf units. please try again.

**Comment by amaelkady** [comment]
@liomessi-10 also please sned a screen shot of the f,-2d/opensees window if the error still exist

**Comment by liomessi-10** [comment]
Thank you for the answer, after the correct definitions of loads the error persist. An image of the error is attached:
![errorFM-2D](https://github.com/amaelkady/FM-2D/assets/71189206/78d28cff-5c4e-40b1-897c-0a63308f35e4)

**Comment by amaelkady** [comment]
@liomessi-10 can you confirm that you are running fm-2d using the fm-2d.exe file in the application folder directly and not using a shortcut

**Comment by liomessi-10** [comment]
Thanks for the reply, using the fm-2d.exe file in the application folder directly worked, however the IDA analysis did not complete. This is the new error: 
![2errorFM-2D](https://github.com/amaelkady/FM-2D/assets/71189206/7b73fdf6-abe4-4547-bce0-fd4a1e0a1170)
Matlab version is R2022b.
