### ISSUE TITLE
Switch to OAuth 2 for OpenStreetMap provider

### ISSUE THREAD

**Issue by danieldegroot2** [amaelkady/FM-2D#3]
Switch to OAuth 2 from HTTP Basic Auth and OAuth 1.0a. They are being deprecated.
See https://github.com/openstreetmap/operations/issues/867

**Comment by mmd-osm** [comment]
@danieldegroot2 : are you sure this project is using osm with oauth 1.0a, or even osm at all? Let's close this one, if it's not relevant.

**Comment by danieldegroot2** [comment]
@amaelkady I would suggest removing [openstreetmap as example](https://github.com/amaelkady/FM-2D/blob/04bfe104919e8b91039137108b6e30f662f3ee24/lib/wub-5.0.0/Domains/OAuth/OAuth.tcl#L352) if you are not actively using it.
