### ISSUE TITLE
The program couldn't create file or folder

### ISSUE THREAD

**Issue by faridpr** [amaelkady/FM-2D#4]
Hello Professor,
Thank you for your great work
I ran into a problem. When I click on the "Get Period" button, I get this error:
```
Error Identifier:   MATLAB:cd:NonExistentFolder
Error Message:      Unable to change current folder to 'D:\Users\Farid\Desktop\fm2D-example\Results' (Name is nonexistent or not a folder).
--------------------------------------------------
Error Location:
----------------
Line   98 in Get_Mass_and_Period
Line  433 in FM2D_App.GetperiodButtonPushed
```
![b](https://github.com/amaelkady/FM-2D/assets/111774106/fedeb64c-86d6-4c3c-905d-877d91105dcc)

Program runned as admin
MATLAB Runtime version: R2022b

**Comment by amaelkady** [comment]
Please make sure that you follow these instructions below (those are also described in the manual):

First, you have to make sure that the Opensees.exe file is running properly within the FM-2D installation directory "C:\Program Files\University of Southampton\FM_2D\application". You should get the window shown below:
![image](https://github.com/amaelkady/FM-2D/assets/39971525/c2b970f7-d270-47c6-adca-08562a95d41b)

If the OpenSees window above shows an error, then download the "lib" folder available on GitHub FM-2D repo and add it to the following directory: "C:\Program Files\University of Southampton\FM_2D"

When running FM-2D, you need to run "as administrator" using the FM-2D.exe file within the "C:\Program Files\University of Southampton\FM_2D\application" directory. If you run it using the desktop shortcut, errors will occur.
