### ISSUE TITLE
Questions about Modeling

### ISSUE THREAD

**Issue by Ya-HengYang** [amaelkady/FM-2D#5]
Hello Prof. Elkady,

I have two questions about the SMF model in this repository:
(1) In the Spring_IMK.tcl (line 89), why do we need to correct rotations to account for elastic deformations? 

`set theta_y  [expr $My/(6 * $E * $Ix / $L)];`
`set theta_p  [expr $theta_p  - ($McMyP-1.0)*$My/(6 * $E * $Ix / $L)];`
`set theta_pc [expr $theta_pc + $theta_y + ($McMyP-1.0)*$My/(6 * $E * $Ix / $L)];`

If we follow the notation in the Appendix B of Ibarra (2005), does that imply that the response parameter (e.g., $\theta_p$) obtained from the regression equation (lines 78 & 79) actually corresponds to $\theta_{p,mem}$ instead of $\theta_{p,spring}$? If so, then it's necessary to eliminate the elastic beam-column term $\theta_{bc}$ to ensure that the sub-elements are connected in series and have the correct assembled member parameters. However, if it is the case, should we use `(n+1)/n *6 * $E * $Ix / $L` instead of  `6 * $E * $Ix / $L` for $K_{bc}$?

(2) In SMF4B.tcl (line545),  what is the reason or reference for defining gravity frame element damping using `$a1_mod/10`?

`region 3 -eleRange  900000  999999 -rayleigh 0.0 0.0 [expr $a1_mod/10] 0.0;`

Thank you!
Best, YHY

**Comment by amaelkady** [comment]
1) Yes, the expressions given by Ibarra (2005) and most similar studies need to be corrected as they don't take into consideration the member discritization employed by different researchers. You could modify the rotation considering the (n+1)/n factor but this effect is small anyway.

2) This is the damping for the nonlinear springs not the gravity columns (please refer to the element notation in the manual). The damping factor in modified by 1/n to account for the stiffness modifictions (Zareian and Medina 2010)..

**Comment by Ya-HengYang** [comment]
Got it. Thank you for the reply!
